### ISSUE TITLE
Unable to successfully install postgres while running fish shell

### ISSUE THREAD

**Issue by emilford** [smashedtoatoms/asdf-postgres#13]
I'm not sure if this is as asdf-postgres plugin issue, but starting here as this is the only plugin with which I've experienced this issue.

For background, I am running on macOS High Sierra with asdf installed via homebrew.

I am attempting to install postgres 9.6.6 alongside an existing postgres 10.1 asdf install. I've come to learn through a bit of digging that this appears to be an issue when installing while running the fish shell.

I kept running into this error on install:

```
prereqdir=`cd 'utils/' >/dev/null && pwd` && \
	  cd '../../src/include/utils/' && rm -f errcodes.h && \
	  ln -s "$prereqdir/errcodes.h" .
/bin/sh: line 0: cd: utils/: No such file or directory
make[3]: *** [../../src/include/utils/errcodes.h] Error 1
make[2]: *** [submake-errcodes] Error 2
make[1]: *** [all-common-recurse] Error 2
make: *** [all-src-recurse] Error 2
```

Again, digging a bit more this evening, I realized that I hadn't yet switched my default shell to fish shell when the install of postgres 10.1 was successful. Now attempting to install postgres 9.6.6, my default shell has been set to fish shell and I continuously receive the above the error.

Sure enough, switching my shell back to the default bash shell and attempting to install 9.6.6 runs without issue. And looking at the error output now, fish shell doesn't allow for the `command 1 && command 2` syntax and instead uses `command 1; and command 2` format.

So definitely not sure that this is anything to do with the plugin, but starting here to hopefully document for anyone else experiencing this issue and to make sure there isn't anything I'm missing on my end.

**Comment by smashedtoatoms** [comment]
I haven't used fish at all, but I have other examples of problems like this.  I am going to have to figure out if I can do anything about it.  I appreciate you calling it out.  Sorry I took almost 2 years to respond.  I am scum.

**Comment by smashedtoatoms** [comment]
I am closing this ticket.  I am not using fish shell and don't have time to figure this out.  If someone wants to submit a PR for it, I'd be glad to work through it, but I can't roll it from scratch right now.  Thanks and sorry.
