### ISSUE TITLE
Manage postgres with brew services?

### ISSUE THREAD

**Issue by dideler** [smashedtoatoms/asdf-postgres#14]
One of the benefits of installing postgres via brew is you can manage it with brew services.

Is there a way to install postgres via asdf and still manage it via brew services?

**Comment by smashedtoatoms** [comment]
I don’t know enough about brew services to know for sure, but I kind of doubt it. Brew is for system wide installs, and this was originally made for per-project installs to allow lots of different versions to be installed without collisions. This wasn’t really meant to be a system wide Postgres installer. I suspect people are doing it, but it likely requires a more manual bespoke config.

**Comment by dideler** [comment]
Thanks Jason, I'll close this.

**Comment by prem-prakash** [comment]
I am curious, why compile it if we can get the binaries ready to go?

**Comment by smashedtoatoms** [comment]
There are lots more options available if you compile.
