### ISSUE TITLE
Postgres "install-docs" or "install-world"

### ISSUE THREAD

**Issue by volodymyrshevhuk** [smashedtoatoms/asdf-postgres#18]
Hi. Does it make sense to add "make install-docs" as final step of postgres installation to create man pages?
Also "make install-world" can be used instead of "make install" to achieve the same goal. 

From postgres installation docs:
"To install the documentation (HTML and man pages), enter: make install-docs"

https://www.postgresql.org/docs/current/install-procedure.html

**Comment by smashedtoatoms** [comment]
If you want to do it and create a pull request I'll pull it in.  I had never intended this to get used as much as it does, and I didn't really plan on it being used to create anything more than ephemeral postgres instances on local dev boxes for people that were pretty familiar with postgres to start with, so the thought never crossed my mind.

**Comment by smashedtoatoms** [comment]
If you want to do it and create a pull request I'll pull it in. I had never intended this to get used as much as it does, and I didn't really plan on it being used to create anything more than ephemeral postgres instances on local dev boxes for people that were pretty familiar with postgres to start with, so the thought never crossed my mind.
