### ISSUE TITLE
reshim doesn't work 

### ISSUE THREAD

**Issue by tz4678** [smashedtoatoms/asdf-postgres#19]
```bash
$ asdf list postgres 
  11.4
$ asdf reshim postgres 11.4                  
$ sudo pg_ctl start -D /var/lib/postgres/data
unknown command: pg_ctl. Perhaps you have to reshim?

```

**Comment by smashedtoatoms** [comment]
Hrm, weird.  Can you run `asdf reshim postgres` and not specify the version and let me know what it does?

**Comment by itsthatguy** [comment]
Have you previously set `$PG_DATA`? That would cause pg_ctl to not be found in the shims

**Comment by smashedtoatoms** [comment]
I am going to close this as I haven't heard about it being a repeated issue.  Feel free to re-open if you need to.
