### ISSUE TITLE
Can't install 9.6.2 or 10.1

### ISSUE THREAD

**Issue by mu1664al-s** [smashedtoatoms/asdf-postgres#20]
Hello world. I am running Ubuntu 18.04 with brew and all the dependencies install. I am unable to install v9.6.2 and 10.1. I haven't tried installing any other version yet. This is what I get:

copy_fetch.c:159:1: error: conflicting types for ‘copy_file_range’
 copy_file_range(const char *path, off_t begin, off_t end, bool trunc)
 ^~~~~~~~~~~~~~~
In file included from copy_fetch.c:15:0:
/usr/include/unistd.h:1110:9: note: previous declaration of ‘copy_file_range’ was here
 ssize_t copy_file_range (int __infd, __off64_t *__pinoff,
         ^~~~~~~~~~~~~~~
<builtin>: recipe for target 'copy_fetch.o' failed
make[3]: *** [copy_fetch.o] Error 1
make[3]: Leaving directory '/tmp/tmp.b3pbJI5vEw/postgresql-10.1/src/bin/pg_rewind'
Makefile:40: recipe for target 'all-pg_rewind-recurse' failed
make[2]: *** [all-pg_rewind-recurse] Error 2
make[2]: Leaving directory '/tmp/tmp.b3pbJI5vEw/postgresql-10.1/src/bin'
Makefile:37: recipe for target 'all-bin-recurse' failed
make[1]: *** [all-bin-recurse] Error 2
make[1]: Leaving directory '/tmp/tmp.b3pbJI5vEw/postgresql-10.1/src'
GNUmakefile:11: recipe for target 'all-src-recurse' failed
make: *** [all-src-recurse] Error 2

Any ideas on what to do?

**Comment by smashedtoatoms** [comment]
I have never used brew in Ubuntu, so I am not sure if that is the cause of your issues or not.  I guess I'd start with trying to install dependencies via apt: `sudo apt-get install linux-headers-$(uname -r) build-essential libreadline-dev` or see if you can make sure those are installed with brew.  I can set up a Ubuntu 18.04 docker container and try it out, but I won't have a chance until later this week.

**Comment by mu1664al-s** [comment]
Looks like two of the updated libraries in Ubuntu 18.04 is causing this problem for version 10.1 and lower. I ended up with installing 10.2.
