### ISSUE TITLE
Please help me install asdf-postgres on OSX with a functioning SSL

### ISSUE THREAD

**Issue by sparta-developers** [smashedtoatoms/asdf-postgres#28]
I need to access remote databases with SSL, normally automatically established via psql.

The asdf psql ssl seems to be broken.

I've attempted to provide build flags to use openssl installed via homebrew. Here are the contents of my `~/.asdf-postgres-configure-options` file:

```
POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libs=/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/opt/openssl@1.1/include"
```

When I install postgres with asdf, it fails with:
```
duplicate symbol _PQsslStruct in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol _PQsslAttributeNames in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol _PQgetssl in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol _PQsslAttribute in:
    fe-secure.o
    fe-secure-openssl.o
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libpq.5.11.dylib] Error 1
make[2]: *** [all-libpq-recurse] Error 2
make[1]: *** [all-interfaces-recurse] Error 2
make: *** [all-src-recurse] Error 2
```
I'm out of my depth on this. Any suggestions?

**Comment by sparta-developers** [comment]
We succeeded in building postgres with openssl on OSX. Here are the contents of our `~/.asdf-postgres-configure-options`

```
POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include"
```

**Comment by smashedtoatoms** [comment]
Sorry I didn't get back to you all in time.  I am glad you figured it out.  I am adding your code as an example to the README so others can gain from your pain.  Thanks for chasing it down, and sorry again for not getting back to you.

**Comment by jbranchaud** [comment]
I've run into this exact same issue attempting to install Postgres 11.11 with OpenSSL support. I've tried several combinations that all lead to the same 4 duplicate symbols listed above. I had no linker issues when building Postgres 13 with OpenSSL.

Different combinations I've tried:

_This is what worked for me with Postgres 13, but swapping in 11.11 now._

```
$ POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl/lib --with-includes=/usr/local/include:/usr/local/opt/openssl/include" asdf install postgres 11.11
```

_Swapping the libraries and includes over to `openssl@1.1`_

```
$ POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include" asdf install postgres 11.11
```

_Including the `--with-uuid=e2fs` (not sure what this flag is for)_

```
$ POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include" asdf install postgres 11.11
```

**Comment by JonRowe** [comment]
I have duplicate symbols on 13.3 on Catalina and no combination of the flags in issues are fixing it, it seems theres  flag for ld to ignore duplicate symbols but I have no idea how to configure the build to pass it

**Comment by JonRowe** [comment]
13.4 and updated build tools combined with the flags from homebrew seems to have fixed it, nfi how

**Comment by smashedtoatoms** [comment]
Sounds right. I'm really sorry. I will never get the time back that I have wasted on this issue across multiple projects.

**Comment by JonRowe** [comment]
No need to apologise, your time and effort is greatly appreciated, I am now trying to rebuild 13.3 with more and more minimal flags to try to find that was the "magic incantation" :joy:

**Comment by JonRowe** [comment]
As an aside, if you need `icu` on OS X with home brew, you need this in your shell (not just in the `~/.asdf-postgres-configure--options` but if you the file on the top level it works):
```
export ICU_CFLAGS="-I$(brew --prefix icu4c)/include"
export ICU_LIBS="-L$(brew --prefix icu4c)/lib -licui18n -licuuc -licudata"
```

Having it

**Comment by JonRowe** [comment]
In fact 13.3 still seems not to compile, so perhaps its a genuine error in the postgres source that homebrew is somehow patching?

**Comment by smashedtoatoms** [comment]
Alright, I just put another attempt to get it working up.  It have it set up to use openssl, readline, zlib, curl, and uuid by default.  I compiled 11.11, 13.3, 14.1 and 9.6.8 on an m1 mac running 11.6 and on ubuntu 20.04 in a docker container and both worked.  I don't have the time or the hardware to try it on much more.  It add' quite a list of dependencies, which I added to the readme.  I am going to close this ticket.  If any of you have issues, let me know what you ran into and I will see if I can get them fixed.

**Comment by JonRowe** [comment]
🙌 thank you!

**Comment by momolog** [comment]
Just installed postgres 13.3 with asdf and no further env setup and it worked like a charm. Thank you so much!

**Comment by joelparkerhenderson** [comment]
Here's what worked for me. I'm using macOS 12.4, homebrew, OpenSSL 1.1, UUID via e2fs, and deliberately using the homebrew installation location for SSL. 

Install OpenSSL:

```sh
$ brew install openssl@1.1
$ brew --prefix openssl@1.1
/opt/homebrew/opt/openssl@1.1
```

The uuid-ossp module generates universally unique identifiers (UUIDs).
The uuid-ossp module can now be built without the OSSP library on some 
platforms. On macOS, suitable functions are provided by using "e2fs" in the 
libuuid library, which originally came from the e2fsprogs project.

```sh
brew install gcc readline zlib curl openssl@1.1
asdf plugin-add postgres
POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-openssl --with-uuid=e2fs --with-libraries=/usr/local/lib:/opt/homebrew/opt/openssl@1.1/lib --with-includes=/usr/local/include:/opt/homebrew/opt/openssl@1.1/include" asdf install postgres latest
```

Success looks like this:

```sh
You can now start the database server using:

~/.asdf/installs/postgres/14.4/bin/pg_ctl -D ~/.asdf/installs/postgres/14.4/data -l logfile start
```

**Comment by kenichi** [comment]
I'm not able to install postgres-14.3, as defined in a project's `.tool-versions` file. I've tried various combinations of the above as well as a clean env; alas, no luck. Apologies in advance if there is a better thread or happy to create a new issue if you prefer.

I'm on an m1, macOS 12.4, homebrew, zsh, Xcode+clang/llvm. I have gcc (11.3), readline, zlib, curl, openssl@1.1 all installed via homebrew.

Clean environment running `asdf install postgres` yields clang errors about .o files:

```
% asdf install postgres
...
Building with options: --prefix=/Users/kenichi/.asdf/installs/postgres/14.3     --with-uuid=e2fs     --with-openssl     --with-zlib     --wit
h-libraries='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/openssl/lib:/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/
openssl/lib:/opt/homebrew/libressl/lib:/opt/homebrew/lib:/usr/local/lib:/usr/lib'     --with-includes='/opt/local/lib:/sw/lib:/usr/local/opt/
openssl/include:/opt/homebrew/opt/openssl/include:/opt/homebrew/include:/opt/homebrew/opt/openssl@1.1/include:/opt/homebrew/openssl/include:/
opt/homebrew/libressl/include:/opt/homebrew/include:/usr/local/include:/usr/local/lib:/usr/lib'
...
clang: error: no such file or directory: 'utils/mmgr/memdebug.o'
clang: error: no such file or directory: 'utils/mmgr/portalmem.o'
clang: error: no such file or directory: 'utils/mmgr/slab.o'
clang: error: no such file or directory: 'utils/resowner/resowner.o'
clang: error: no such file or directory: '../../src/timezone/localtime.o'
clang: error: no such file or directory: '../../src/timezone/pgtz.o'
clang: error: no such file or directory: '../../src/timezone/strftime.o'
make[2]: *** [postgres] Error 1
make[1]: *** [all-backend-recurse] Error 2
make: *** [all-src-recurse] Error 2
```

Setting CC and CXX to homebrew's GCC yields similar:

```
% export CC=/opt/homebrew/opt/gcc/bin/gcc-11                                                                     
% export CXX=/opt/homebrew/opt/gcc/bin/g++-11                                                                    
% asdf install postgres                                                                                          
Building with options: --prefix=/Users/kenichi/.asdf/installs/postgres/14.3     --with-uuid=e2fs     --with-openssl     --with-zlib     --wit
h-libraries='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/openssl/lib:/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/
openssl/lib:/opt/homebrew/libressl/lib:/opt/homebrew/lib:/usr/local/lib:/usr/lib'     --with-includes='/opt/local/lib:/sw/lib:/usr/local/opt/
openssl/include:/opt/homebrew/opt/openssl/include:/opt/homebrew/include:/opt/homebrew/opt/openssl@1.1/include:/opt/homebrew/openssl/include:/
opt/homebrew/libressl/include:/opt/homebrew/include:/usr/local/include:/usr/local/lib:/usr/lib' 
...
ld: file not found: access/brin/brin.o
collect2: error: ld returned 1 exit status
make[2]: *** [postgres] Error 1
make[1]: *** [all-backend-recurse] Error 2
make: *** [all-src-recurse] Error 2
```

It may be worth noting that attempting to build vanilla 14.3 source with similar configure options gets to a completely different error:

```
% ./configure --with-openssl --with-uuid=e2fs --with-zlib
...
% make
...
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -I/opt/homebrew/include -O2 -g -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/zlib/include -pthread -D_REENTRANT -D_THREAD_SAFE -D_POSIX_PTHREAD_SEMANTICS  -I../include -I../../../../src/interfaces/ecpg/include -I../../../../src/interfaces/libpq -DFRONTEND -I../../../../src/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -I/opt/homebrew/opt/ruby/include  -DSO_MAJOR_VERSION=3  -c -o informix.o informix.c
informix.c:97:14: error: use of undeclared identifier 'CDECIMALTYPE'
        if (risnull(CDECIMALTYPE, (char *) arg1) || risnull(CDECIMALTYPE, (char *) arg2))
...
```

Any help would be greatly appreciated!

**Comment by joelparkerhenderson** [comment]
^@kenich Yes unixodbc has a long history of interfering with postgres, and what you're describing looks like it's possibly a path issue.

You may want to look at your paths (such as `echo $PATH`) to see if you perhaps are usinunixodbc on a path (such as /usr/local) that comes before your postgres path (such as `/opt/homebrew` or `.asdf/installs/`). 

Try setting asdf to be first in your path: 

```
export PATH="/Users/kenichi/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:$PATH"
```

Delete any work in progress (such as `rm ~/.adsf/installs/postgres/` or in  your manual work `make clean`). Then retry.

Something that has helped me quite a lot with homebrew paths over many years is to create a distinct macOS user "brew" and use it to install all the brew stuff. This ensures that the "brew" account has mostly vanilla paths, and is mostly consistent over time. Note that this is NOT a typical setup, and the maintainer of brew says this is NOT a supported setup. YMMV. Good luck!
