### ISSUE TITLE
Does asdf-postgres adds postgresql.service

### ISSUE THREAD

**Issue by byteshiva** [smashedtoatoms/asdf-postgres#30]
Does asdf-postgres adds postgresql.service for latest installation of PostgreSQL?

**Comment by smashedtoatoms** [comment]
Negative. It was developed so I could install specific Postgres instances per micro service for dev and be programmatically invoked for testing. None of the niceties for running it long-term locally have gotten any love. PRs are welcome, but there are probably better solutions for those cases.

**Comment by byteshiva** [comment]
> Negative. It was developed so I could install specific Postgres instances per micro service for dev, and be programmatically invoked for testing. None of the niceties for running it long-term locally have gotten any love. PRs are welcome, but there are probably better solutions for those cases.

but there are probably better solutions for those cases.
> What solution are you referring here, can you mind sharing it.

**Comment by smashedtoatoms** [comment]
Off the top of my head maybe brew or something if you are on mac, or apt on ubuntu.  I am not sure.  I haven't spent much time thinking about this in any context other than dev... mostly because I suck at managing databases, and I use hosted dbs in prod so I don't have to think about it.

**Comment by byteshiva** [comment]
> Off the top of my head maybe brew or something if you are on mac, or apt on ubuntu. I am not sure. I haven't spent much time thinking about this in any context other than dev... mostly because I suck at managing databases, and I use hosted dbs in prod so I don't have to think about it.

I'm aware of `brew and apt` and also `flatpak` , `docker` all comes with there own little constraints, The asdf is quick and easy to manage versions. Also, as part of prototype engineering some of the  requirements are to install different versions of a run-time say mongodb etc and work on it. Hence I choose asdf. As of now its working good.

**Comment by smashedtoatoms** [comment]
Sorry, I have been neglecting this issue.  I am not going to have the time to implement this as a service.  As I said, I will welcome PRs.  I'm glad it's working for you.  Thanks and sorry.
