### ISSUE TITLE
configure: error: header file <ossp/uuid.h> or <uuid.h> is required for OSSP UUID

### ISSUE THREAD

**Issue by churcho** [smashedtoatoms/asdf-postgres#31]
Environment: MacOS

My ..asdf-postgres-configure-options has `POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=ossp"`

Can't seem to be able to install 12.2

**Comment by smashedtoatoms** [comment]
What errors are you getting?

**Comment by churcho** [comment]
When the installation is ongoing I get `configure: error: header file <ossp/uuid.h> or <uuid.h> is required for OSSP UUID` and it stops.

**Comment by smashedtoatoms** [comment]
Ok, you on a mac?

**Comment by churcho** [comment]
> Ok, you on a mac?
Yes I am

**Comment by smashedtoatoms** [comment]
Cool.  How are you installing ossp?  Are you using brew `ossp-uuid`?

**Comment by churcho** [comment]
I did a `brew install ossp-uuid` and it's in `/usr/local/Cellar/ossp-uuid/1.6.2_2:`

**Comment by smashedtoatoms** [comment]
Can you try `POSTGRES_EXTRA_CONFIGURE_OPTIONS="-DWITH_UUID=ossp"` and let me know what it does?

**Comment by churcho** [comment]
> Can you try `POSTGRES_EXTRA_CONFIGURE_OPTIONS="-DWITH_UUID=ossp"` and let me know what it does?

Is that a valid env specification?
Doesn't match any of the ones I have seen before. Actually errors out when asdf sources the file

**Comment by smashedtoatoms** [comment]
I am not sure, sounds like probably not.  I am not on a machine I can test it out with right now and am trying to Dr. Google it.  I am still on postgres 10.7, and installed mine with e2fs for uuid.  I haven't tried it with ossp-uuid, so I am kind of flying blind.

**Comment by churcho** [comment]
No worries. Let me know when you have time to test on a machine. I will keep exploring.
What function do you use to create uuid when using `e2fs`?

**Comment by smashedtoatoms** [comment]
`POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=e2fs asdf install postgres 10.7` is what I used for postgres 10.7

**Comment by smashedtoatoms** [comment]
That in combination with running `create extension if not exists "uuid-ossp"` gets me my `uuid_generate_v4()` function to use as default for uuid keys
.

**Comment by churcho** [comment]
> `POSTGRES_EXTRA_CONFIGURE_OPTIONS=--with-uuid=e2fs asdf install postgres 10.7` is what I used for postgres 10.7

I was able to install with this.

**Comment by smashedtoatoms** [comment]
Cool.  That is unfortunately the only one I have used, so it's the only one I know about.
