### ISSUE TITLE
Download binaries

### ISSUE THREAD

**Issue by JPYamamoto** [smashedtoatoms/asdf-postgres#32]
Is there a way to just download and install the binaries instead of having to build them?

**Comment by smashedtoatoms** [comment]
I have not added that capability.  It always builds as of now.  I can look into it, but it won't be soon as I am buried for at least the next month.

**Comment by smashedtoatoms** [comment]
I am not going to have the time to get to this.  Especially with the new M1 macs, I think the build is actually going to be the better way to do this for a while.  If someone wants to do it though and make it configurable, I'd accept the PR.  Thanks and Sorry.
