### ISSUE TITLE
Running multiple postgres versions simultaneously

### ISSUE THREAD

**Issue by tanweerdev** [smashedtoatoms/asdf-postgres#34]
How can run `multiple postgres versions` by specifying port for each version eg for 13.0 version I want to specify port 5130 => 5 13(major) 0 patch. and for lets say 12.3, port should be 5123. Perhaps, this hack should be part of Readme. Thanks in advance

**Comment by smashedtoatoms** [comment]
That is a more loaded question than you might think. You either need to add a config file and reference it when you start up Postgres or use the -p flag.  It comes down t how you start postgres.  That's not as much part of the installer as it is part of Postgres itself.

**Comment by tanweerdev** [comment]
Ok. can you please help me setup this config file. That would be awesome. because I have tried creating a config failed and it failed to set port

**Comment by smashedtoatoms** [comment]
I'd start with just using the -p flag. If you want to use the config file, it customarily sits in the same directory as wherever you specify your data directory. So, you can drop the config file into ~/.asdf/installs/postgres/whatever_your_version_is/ and it will pick it up. If you're specifying that location, just out your config alongside where you specify your data file location.

**Comment by tanweerdev** [comment]
I tried this config(got it from Readme I think)
```
cat ~/.asdf-postgres-configure-options
--with-pgport=5130
```
But it didnt work. So you are suggesting in this folder, I create ~/.asdf/installs/postgres/whatever_your_version_is/ a config file lets call it `postgres-configure-options` with content `-p 5310` . But how and where do I tell asdf to load these configs each time it  tries to start this specific version of postgres

**Comment by smashedtoatoms** [comment]
I might be misunderstanding what you're trying to do.  You can't have that file sitting in your home directory and expect it to work.  Postgres has no way to know where it is unless you explicitly tell it.  It's easier to just use the defaults unless you have a reason not to.  Also, the --with-pgport is for compiling in the default port on build, not for setting it after the fact.  

If your goal is to compile it in, you need to install postgres with something like  `POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-pgport=5130" asdf install postgres`.  

If, for example, your goal is to add a config file to specify the port for postgres 9.4.7.  You create a file called `~/.asdf/installs/postgres/9.4.7/postgresql.conf` that contains:

```
port = 5130
```

Stop and start postgres `pg_ctl stop && pg_ctl start`, and you should be good to go.

Does that make sense?

**Comment by tanweerdev** [comment]
Hi @smashedtoatoms I followed your instructions and I have
```
~/.asdf/installs/postgres/13.0$ cat postgresql.conf 
port = 5130
```
and then I restarted pg by `pg_ctl stop && pg_ctl start` but it didnt work(pg still listening on 5432). I have only 13.0 currently installed but need to have 12.something version too along with 10.sth version

**Comment by smashedtoatoms** [comment]
Is your data file sitting in that directory?  I am going to have to install 13.0 and see if I can figure out why it isn't working.  I won't be able to do that until tomorrow.  As a stop-gap, can you try to start it with `pg_ctl -o "-p 5130" start`.  That should at least let you work around it for now.

**Comment by tanweerdev** [comment]
```
~/.asdf/installs/postgres/13.0$ ls
bin  data  include  lib  logfile  postgresql.conf  share
```
But This command `pg_ctl start -o "-p 5130"` worked. Thanks

**Comment by tanweerdev** [comment]
Hi @smashedtoatoms is this now working? with below steps:
```
~/.asdf/installs/postgres/13.0$ cat postgresql.conf 
port = 5130
```
I see you have closed the issue

**Comment by smashedtoatoms** [comment]
I did.  The docs specify that you can modify the postgresql.conf in your data directory.  To test, I updated the port in `~/.asdf/installs/postgres/13.1/data/postgresql.conf` and it works.  I have also verified that it works via cli.  All of this configuration is part of postgres and not asdf-postgres, so I am closing the issue.  Let me know if you have trouble with it though, and I can see what I can do to help.
