### ISSUE TITLE
Bug: List all doesnt work

### ISSUE THREAD

**Issue by volodymyr-sh** [smashedtoatoms/asdf-postgres#35]
Hi. 
On Ubuntu 20.04 with curl curl 7.68.0, grep 3.4 and bash 5.0.17 the command
```bash
curl -s https://ftp.postgresql.org/pub/source/ | grep -Eoh '>v[0-9]+(\.[0-9]+(\.[0-9]+)?|beta[0-9]+)<'
```
which used for retrieving available Postgresql versions doesn't return anything.

The output of 
```
curl -s https://ftp.postgresql.org/pub/source/
```
is something like 
```
<html>
<head><title>Index of /pub/source/</title></head>
<body bgcolor="white">
<h1>Index of /pub/source/</h1><hr><pre><a href="../">../</a>
<a href="v1.08/">v1.08/</a>                                             22-Mar-2006 20:46                   -
<a href="v1.09/">v1.09/</a>                                             22-Oct-2006 00:19                   -
<a href="v10.0/">v10.0/</a>                                             05-Oct-2017 12:47                   -
<a href="v10.1/">v10.1/</a>                                             09-Nov-2017 14:07                   -
...
<a href="v9.6.8/">v9.6.8/</a>                                            01-Mar-2018 12:27                   -
<a href="v9.6.9/">v9.6.9/</a>                                            10-May-2018 14:01                   -
</pre><hr></body>
</html>
```

Looks like the regex should be updated to ` '>v[0-9]+(\.[0-9]+(\.[0-9]+)?|beta[0-9]+)/<'` with `/` at the end before `<` to parse versions correctly

**Comment by smashedtoatoms** [comment]
As if I needed more reasons to hate regex scraping html... let me take a look at this today and see if I can figure out a better way to do this. Are you blocked by this, or were you able to install what you wanted after manually looking it up?

**Comment by smashedtoatoms** [comment]
closed by https://github.com/smashedtoatoms/asdf-postgres/commit/8a0d8b0f30561a3ad19a7f2365515af2fd752854

**Comment by smashedtoatoms** [comment]
closed by https://github.com/smashedtoatoms/asdf-postgres/commit/8a0d8b0f30561a3ad19a7f2365515af2fd752854
