### ISSUE TITLE
Cannot install or list any versions

### ISSUE THREAD

**Issue by zubin** [smashedtoatoms/asdf-postgres#36]
Hello!

For some reason, I can't install postgres:

```sh
$ asdf plugin add postgres
$ asdf install postgres latest
postgres  is already installed
$ which psql
psql not found
$ asdf list postgres 
  No versions installed
$ asdf list all postgres
$ 
```

Note that `list all` isn't returning anything (as per #35). 

Btw this is on macOS Big Sur with an M1 chip. Also asdf is new to me.

**Comment by smashedtoatoms** [comment]
Ok, I don't really have any way to test that. Let me fix 35 and then we can go from there.

**Comment by smashedtoatoms** [comment]
Issue #35 was causing this.  It has been fixed via https://github.com/smashedtoatoms/asdf-postgres/commit/8a0d8b0f30561a3ad19a7f2365515af2fd752854, so you should be good to go.  If this doesn't fix it, go ahead and re-open the ticket.  

Also, your commands are not quite right `asdf plugin-add postgres` and `asdf list-all postgres` should work now.

**Comment by smashedtoatoms** [comment]
Oh, also, `asdf install postgres latest` won't work.  You do need to specify a version.

**Comment by zubin** [comment]
Thanks, it's working now! 🎉 

Btw `asdf install postgres latest` worked for me, and `asdf list all` appears to be equivalent to `asdf list-all` (same with `plugin-add` etc). 

Here are the steps, if anyone else needs them:

```sh
brew unlink asdf
brew install asdf --HEAD
asdf plugin remove postgres
asdf plugin add postgres
asdf install postgres latest
```

**Comment by smashedtoatoms** [comment]
Oh that is great.  I wonder if I just need to update my asdf install or something.  That's good to know.  Thanks for following up!

**Comment by smashedtoatoms** [comment]
This is actually a pretty good justification for keeping it installing from source if it worked on the M1 too.  Thanks for spending the time on this.
