### ISSUE TITLE
Unable to install Postgres 12.4 with SSL support on MacOSX BigSur

### ISSUE THREAD

**Issue by momolog** [smashedtoatoms/asdf-postgres#37]
I am on 
* MacOSX 11.1 
* ASDF version v0.8.0-c6145d0 and 
* postgres plugin version e2f0c4b

I have a file `~/.asdf-postgres-configure-options` containing
```
POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include"
```
as mentioned in the README (btw. should `--with-openssl` not be a default?)

Running `asdf install postgres 12.4` succeeds. 
But when I do `psql -c ssl=on` I get this error:
```
psql: error: could not connect to server: server does not support SSL, but SSL was required
```

What am I missing?

**Comment by smashedtoatoms** [comment]
How are you sourcing `~/.asdf-postgres-configuration-options`?  If you run `echo $POSTGRES_EXTRA_CONFIGURE_OPTIONS` and get a blank line, your config options are not exporting.  If you're not exporting `POSTGRES_EXTRA_CONFIGURE_OPTIONS` before you run `asdf install`, you're going to get a vanilla postgres install.  

Can you uninstall your current 12.4 and try: `POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include" asdf install postgres 12.4`?  Another option would be to drop the `POSTGRES_EXTRA_CONFIGURE_OPTIONS` export into your `.profile` or `.zshrc`, or `.envrc` or whatever your preferred mechanism is for exporting environment variables?  It should work then.  I am not sure what you were going for with the `~/.asdf-postgres-configure-options` file.  It may be that I am misunderstanding how your environment is set up.

As for why it isn't included by default, your `POSTGRES_EXTRA_CONFIGURE_OPTIONS` are a great example.  Hopefully those config options will work on your machine.  They won't work on Ubuntu or Arch.  There are a dozen different places and locations for openssl depending on OS and version, and I haven't had the time to figure it out.  When I briefly added a default openssl config for mac, it broke for all the Linux folks.  When I modified it to work for Ubuntu and Arch, it broke for other versions of Ubuntu and Arch, so I just nuked it.  

I use asdf for setting up my dev environments for different projects, so not having SSL isn't a priority for me.  If that changes, I may have to set aside the time.  If someone else comes along that needs it and wants to get it working at least for LTS Ubuntu, Mac, and Arch, I'd accept the PR.  

Let me know if doing it inline works for you or not.

**Comment by momolog** [comment]
Thanks for the immediate reply! 
Your proposed solution works.

I was under the impression that asdf-postgres somehow sources the file automatically (I had just skimmed over [this issue](https://github.com/smashedtoatoms/asdf-postgres/issues/28)).

Thanks a lot.

Btw. I am still a bit puzzled that `--with-openssl` is not a default - if not of asdf-postgres then of postgres itself.

**Comment by smashedtoatoms** [comment]
It is default on the prebuilt binary. I haven't added an option to use a prebuilt binary yet. That's probably the ultimate solution, although it has its own unique problems. If I default to a prebuilt binary, and build from source via a configuration flag that might be a solid compromise. I will look into that.
