### ISSUE TITLE
heroku pg:psql does not work with asdf

### ISSUE THREAD

**Issue by sobrinho** [smashedtoatoms/asdf-postgres#41]
**Describe the bug**

```
$ psql --version
psql (PostgreSQL) 13.1

$ type psql
psql is /Users/sobrinho/.asdf/shims/psql

$ heroku pg:psql --remote production
--> Connecting to [redacted]
psql: error: FATAL:  no pg_hba.conf entry for host "[redacted]", user "[redacted]", database "[redacted]", SSL off
 ▸    psql exited with code 2
```

I didn't investigate though if this is an issue with Heroku CLI but I do have another machine using Homebrew Postgres and it works just fine, exactly the same version of the Heroku CLI/Node.JS.

**Steps to reproduce**

```
asdf install postgres 12.5 # or 13.1
heroku pg:psql --app [some app with postgres on Heroku]
```

**Expected behavior**

A psql session

**Screenshots**

N/A

**Additional context**

The machine failing is M1 and the one working is Intel, not sure if anything changes because of that.

**Comment by momolog** [comment]
@sobrinho I think this issue will help you: https://github.com/smashedtoatoms/asdf-postgres/issues/37
It's about compiling SSL support into the postgres bin.

That will cure the Heroku connection problems.

**Comment by smashedtoatoms** [comment]
This one keeps coming up.  It seems like my initial response to this was wrong.  I will spend some time on it this weekend to see if I can get SSL support by default for 64-bit intel/arm mac, and intel ubuntu, and then let people open PRs for other platforms. @sobrinho, if you can do what @momolog suggested, it should unblock you for now.  I'm sorry this has been such a pain.

**Comment by sobrinho** [comment]
Maybe you could do what ruby-build does, it installs a openssl for each installed ruby so that way it won't depend on the library be available in the system and won't break if anything is installed/uninstalled/upgraded/etc.

Not sure how much effort it would be, though.

**Comment by sobrinho** [comment]
I just read about using prebuilt binaries, that may be the way to go too.

**Comment by smashedtoatoms** [comment]
This is such a dumpster fire.  I don't know why Apple can't get its shit together when it comes to openssl.  Every release is a new travesty when it comes to linked libraries.  I attached the errors below.  The linker is basically linking anything it finds, which makes it really hard to build without doing a bespoke config for every mac on the planet.  I have no idea how to get this to build for multiple versions of darwin running multiple versions of Brew and MacPorts.  Maybe it's easy and obvious, but I am just not seeing it.  I actually can't get it to build at all on my M1 mac with Brew, but I can with MacPorts.  

I am not using this plugin right now.  I don't have time to fuck with it.  If someone wants to take a stab at either converting the whole thing to use prebuild binaries (which sucks because I would really like it to be configurable) or figure out how to make linking to openssl less of an affront to god on macs, I will gladly accept the PR.  I'm sorry.  I just don't have time to chase this around and around right now.  

```
duplicate symbol '_PQsslStruct' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQsslAttributeNames' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQgetssl' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQsslAttribute' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQdefaultSSLKeyPassHook_OpenSSL' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQsetSSLKeyPassHook_OpenSSL' in:
    fe-secure.o
    fe-secure-openssl.o
duplicate symbol '_PQgetSSLKeyPassHook_OpenSSL' in:
    fe-secure.o
    fe-secure-openssl.o
```

**Comment by sobrinho** [comment]
That's probably one of the reasons ruby-build decides to build its owns OpenSSL for each installed ruby.

I will take a look at that when, and if, I find some spare time.

**Comment by smashedtoatoms** [comment]
I'll take a look as well one of these weekends when I have some time. Sorry for being so grumpy.  This just seems like something that should take 4 minutes to fix, and instead, it's a total time vampire.

**Comment by sobrinho** [comment]
No worries, thanks for spending your time on the project! ❤️

**Comment by JonRowe** [comment]
I think these issues need to be reopened, closing them makes it seem like its fixed and its anything but, I appreciate that its a time suck you don't have time for, but theres no shame in leaving issues open whilst they are unfixed

**Comment by JonRowe** [comment]
Heroku in particular when running from a shimmed directory will use the client from asdf so really it needs openssl support

**Comment by smashedtoatoms** [comment]
> I think these issues need to be reopened, closing them makes it seem like its fixed and its anything but, I appreciate that its a time suck you don't have time for, but theres no shame in leaving issues open whilst they are unfixed

That's a fair point. I'll reopen and see if I can take another look. If not, the open ticket might inspire someone.

**Comment by smashedtoatoms** [comment]
Alright, I just put another attempt to get it working up.  It have it set up to use openssl, readline, zlib, curl, and uuid.  I compiled 14.1 and 9.6.8 on an m1 mac running 11.6 and on ubuntu 20.04 in a docker container and both worked.  I don't have the time or the hardware to try it on much more.  I am going to close this ticket.  If any of you have issues, let me know what you ran into and I will see if I can get it fixed.

**Comment by JonRowe** [comment]
💜 🧡 💛 💚 💙

**Comment by yrashk** [comment]
I just tested the latest update, and it worked on my m1max (Monterey 12.0.1). Amazing! 🤟 Thank you so much.

**Comment by smashedtoatoms** [comment]
That's great news!
