### ISSUE TITLE
configure: error: Cannot find a working 64-bit integer type.

### ISSUE THREAD

**Issue by dankram** [smashedtoatoms/asdf-postgres#42]
**Describe the bug**

Trying to install postgres@9.6.18 through asdf and getting the above error.

**Steps to reproduce**

1. brew install asdf
2. Added "postgres 9.6.18" to my .tool-versions file
3. run asdf install in tool-versions directory

**Expected behavior**

Expected to have postgres install based on the readme included in this repo.

**Screenshots**

<img width="594" alt="Screen Shot 2021-04-09 at 11 03 21 AM" src="https://user-images.githubusercontent.com/295984/114222284-3e1e2480-9923-11eb-9f4c-762513a0ba7d.png">

**Additional context**

Running on mac OS 11.2.2

**Comment by conradbeach** [comment]
I have the same issue when I try to install Postgres 9.5.19. I'm on MacOS 11.2.3 Big Sur.

**Comment by smashedtoatoms** [comment]
I found this:  https://www.postgresql.org/message-id/09A4B554-82B1-4536-B191-2461342EE0BB%40icloud.com. It looks like this is an actual incompatibility with installing postgres on newer mac os version from source for those versions.  If I get a chance, I will see if I can add an option to install from the site instead of from source.  The could also solve issues people have with ssl.  I have no idea when I am going to be able to get to it though.  I am on the process of moving, so my time is pretty tight.

**Comment by dankram** [comment]
Thanks! I know moving can be really stressful so no rush. I can install postgres from brew in the mean time just wanted to make it a bit easier for the developers on our team.

**Comment by conradbeach** [comment]
Thanks for looking into it, @smashedtoatoms. Like @dankram said, I can just use Brew in the meantime.

**Comment by smashedtoatoms** [comment]
I don't think I am going to have time to fix this anytime soon.  The easiest way might be to do a patch, but I haven't been able to carve out enough time to dig into it.  I'll get to this eventually, but it's going to be awhile.

**Comment by conradbeach** [comment]
No worries. Thanks, @smashedtoatoms.

**Comment by chrislo** [comment]
In case it's useful to someone else encountering this error, I was able to install `postgres 9.6.6` on OS X 12.1 by setting a `-Wno-error=implicit-function-declaration` CFLAG, e.g.

```
CFLAGS="-Wno-error=implicit-function-declaration" POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-openssl --with-libraries=/usr/local/lib:/usr/local/opt/openssl@1.1/lib --with-includes=/usr/local/include:/usr/local/opt/openssl@1.1/include" asdf install postgres
```

**Comment by smashedtoatoms** [comment]
@chrislo's workaround is going to have to be as good as it gets for now.  I am sorry all, I don't have the time to go back and clean this kind of thing up on this plugin.
