### ISSUE TITLE
Unable to install selected version

### ISSUE THREAD

**Issue by technowar** [smashedtoatoms/asdf-postgres#44]
**Describe the bug**

Trying to install postgres@10.10 on a dated OS X 10.9.5 machine

**Steps to reproduce**

> $ asdf list all postgres // returns nothing
> $ asdf install postgres 10.10

**Expected behavior**

Expected to install postgres 10.10

**Screenshots**

![Screen Shot 2021-06-29 at 12 04 06 AM](https://user-images.githubusercontent.com/2110456/123668294-8b989680-d86d-11eb-9db2-d9194afbdddb.png)

**Comment by technowar** [comment]
Tried to manually download using curl in verbose mode,
![Screen Shot 2021-06-29 at 12 14 18 AM](https://user-images.githubusercontent.com/2110456/123669779-0910d680-d86f-11eb-80c7-1dfdc485ab2b.png)

**Comment by smashedtoatoms** [comment]
It's failing to download because of an unknown SSL protocol error while connecting to the FTP site.  I can't really do anything about that, unfrotunately.

**Comment by technowar** [comment]
Alright. Thank you.
