### ISSUE TITLE
postgis

### ISSUE THREAD

**Issue by Trevoke** [smashedtoatoms/asdf-postgres#5]
I would very much love to be able to install postgis but I'm not entirely sure how to.

**Comment by smashedtoatoms** [comment]
Postgis can be installed using this instance of postgres, but it has a bunch of other dependencies.  You can install postgres via asdf, which will take care of your postgres dependency. Then install geos, gdal, libxml2, and json-c via homebrew or apt.  Then install proj4 via http://www.markhneedham.com/blog/2015/10/05/mac-os-x-installing-the-proj-4-cartographic-projections-library/, and then install postgis via the README in http://download.osgeo.org/postgis/source/postgis-2.3.3.tar.gz.  It's a giant pain in the ass because of the dependencies, which is why I haven't added it to this.  You can manually get it working, but it's not fun.

**Comment by Aethelflaed** [comment]
After installing the required dependencies, I had to configure postgis with an explicit `--prefix=$(pg_config --configure)` for it to install correctly (he initially wanted to put a dependency inside /usr/local).

Other than that, the installation is pretty much straightforward.

(I'm on archlinux)

**Comment by smashedtoatoms** [comment]
Please let me know if I need to reopen this.

**Comment by peaceful-james** [comment]
A warning for other people installing PostGIS with asdf postgres:

**Don't use the source code linked above! It is very outdated!**

Instead, you should:

Get latest source code as `tar.gz` file from https://postgis.net/source/

It's on version 3 ATOW.

Install the deps. On my system (Trisquel OS), these seem to be:

```
$ sudo apt install build-essential libreadline-dev libxml2-dev libgeos-dev libproj-dev libgdal-dev libprotobuf-c-dev
```

Follow the "Compiling Source" instructions on the PostGIS site. ATOW these are:

```
tar xvzf postgis-3.1.3.tar.gz
cd postgis-3.1.3
./configure
make
make install
```

**Comment by sammkj** [comment]
Here's what works on my Mac:

```zsh
# Download from source then unpack
tar xvzf postgis-3.2.0.tar.gz -C tmp/

cd tmp/postgis-3.2.0

# Configure Postgres path
eval ./configure `pg_config --configure` --with-projdir=/opt/homebrew/Cellar/proj@7/7.2.1

# Follow as instructed
make
make install
```

**Comment by chavenor** [comment]
## Updated 2/14/2022

If you already have POSTGRES installed with asdf and want to add in PostGIS.  

On Mac with M1:
```
brew install proj
brew install protobuf-c
brew install gdal
```

On Linux-ish:
```
sudo apt install build-essential libreadline-dev libxml2-dev libgeos-dev libproj-dev libgdal-dev libprotobuf-c-dev libprotobuf-dev protobuf-c-compiler
```

Make and Install postgis.  Use version compatibile with your Postgres server.  [https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS](url)

```
wgzt https://download.osgeo.org/postgis/source/postgis-3.2.1.tar.gz
tar xvzf postgis-3.2.0.tar.gz -C tmp/
cd tmp/postgis-3.2.0
```

Configure Postgis with your build and project directory.
Note: --with-projdir points to your Mac lib root. This may end in "proj@7/7.2.1" or something like this.  You can find this by ```cd /opt/homebrew/Cellar/``` then look for something that looks like a project.
Note: --with-pgconfig points to the asdf install Postgres installation you want to add the extension to. 
```
eval ./configure `pg_config --configure` --with-projdir=/opt/homebrew/Cellar/proj/8.2.1 --with-pgconfig=/System/Volumes/Data/Users/casey/.asdf/installs/postgres/13.5/bin/pg_config
```

Make and install.   If you get "Nothing to be done for `install'." that still means it was successfull. 
```
make
make install
```

@smashedtoatoms does it make sense to update the README with the above?

Enable the Extension by running the below queries with super privileges. 
```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_raster;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION address_standardizer_data_us;
CREATE EXTENSION postgis_tiger_geocoder;
```

**Comment by P1X3L** [comment]
> ## Updated 2/14/2022
> If you already have POSTGRES installed with asdf and want to add in PostGIS.
> 
> On Mac with M1:
> 
> ```
> brew install geos
> brew install proj
> brew install protobuf-c
> brew install gdal
> ```
> 
> On Linux-ish:
> 
> ```
> sudo apt install build-essential libreadline-dev libxml2-dev libgeos-dev libproj-dev libgdal-dev libprotobuf-c-dev libprotobuf-dev protobuf-c-compiler
> ```
> 
> Make and Install PostGIS. Use version compatible with your Postgres server. [https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS](url)
> 
> ```
> wgzt https://download.osgeo.org/postgis/source/postgis-3.2.1.tar.gz
> tar xvzf postgis-3.2.0.tar.gz -C tmp/
> cd tmp/postgis-3.2.0
> ```
> 
> Configure Postgis with your build and project directory. Note: --with-projdir points to your Mac lib root. This may end in "proj@7/7.2.1" or something like this. You can find this by `cd /opt/homebrew/Cellar/` then look for something that looks like a project. Note: --with-pgconfig points to the asdf install Postgres installation you want to add the extension to.
> 
> ```
> eval ./configure `pg_config --configure` --with-projdir=/opt/homebrew/Cellar/proj/8.2.1 --with-pgconfig=/System/Volumes/Data/Users/casey/.asdf/installs/postgres/13.5/bin/pg_config
> ```
> 
> Make and install. If you get "Nothing to be done for `install'." that still means it was successful.
> 
> ```
> make
> make install
> ```
> 
> @smashedtoatoms does it make sense to update the README with the above?
> 
> Enable the Extension by running the below queries with super privileges.
> 
> ```
> CREATE EXTENSION postgis;
> CREATE EXTENSION postgis_raster;
> CREATE EXTENSION postgis_topology;
> CREATE EXTENSION fuzzystrmatch;
> CREATE EXTENSION address_standardizer_data_us;
> CREATE EXTENSION postgis_tiger_geocoder;
> ```
> 
> @smashedtoatoms does it make sense to update the docs with this? If so feel free to swipe this.

Thanks for your post, I've just made the installation on ubuntu and the correct for linux-ish users is : 
`eval ./configure `pg_config --build` --with-pgconfig=/home/ubuntu/.asdf/installs/postgres/YOUR_VERSION_OF_POSTGRES/bin/pg_config`

**Comment by smashedtoatoms** [comment]
@P1X3L, since postgis is an insanely common tool, I would be fine with a section being added to the README with instructions if you want to add it.

**Comment by nbernardes** [comment]
Thanks @chavenor for the guide! Unfortunately it didn't worked for me, but found another way, that's equal to yours but with just version updates. Here are the step commands I've executed.

```
> Download https://download.osgeo.org/postgis/source/postgis-3.4.2.tar.gz
> tar xvzf postgis-3.4.2.tar.gz
> cd postgis-3.4.2
> eval ./configure `pg_config --configure` \
       --with-projdir=/opt/homebrew/Cellar/proj/9.4.0 \
       --with-pgconfig=/Users/bernardes/.asdf/installs/postgres/16.0/bin/pg_config
> make
> make install
```

After all of this, went into the database and was able to install postgis extension!

**Comment by marka2g** [comment]
I've tried installing postgis so many different ways on a mac M1 arm machine - I finally admit that I'm stuck.  Last attempt was to follow @nbernardes ' recipe using `--with-projdir=/opt/homebrew/Cellar/proj/9.4.0` as I have the same homebrew `proj` package installed; no luck.  My issue comes after successfully running the `./configure` script, during `make`.  Currently I'm getting an error on the `postgis-3.4.2.tar.gz` package: 
`E0000 00:00:1713245269.277517 6670459 command_line_interface.cc:1534] Built-in generator --c_out specifies a maximum edition PROTO3 which is not the protoc maximum 2023.
make[1]: *** [vector_tile.pb-c.c] Error 1
make: *** [all] Error 1`

I run the configure script like so:
`eval ./configure `pg_config --configure`--with-pgconfig=/Users/marksadegi/.asdf/installs/postgres/16.2/bin/pg_config`

also tried setting the `PKG_CONFIG_PATH` env var as per the ./configure output instructions; no luck.

Here's my machine info:
macOS: 14.4.1 
chip: Apple M1 Pro

If anyone has more insight as to how to install `postgis` with an asdf postgres v 16.2 | 16.0 | 15.3 (any would work) install, I would super appreciate the insight!

**Comment by mengqing** [comment]
> I've tried installing postgis so many different ways on a mac M1 arm machine - I finally admit that I'm stuck. Last attempt was to follow @nbernardes ' recipe using `--with-projdir=/opt/homebrew/Cellar/proj/9.4.0` as I have the same homebrew `proj` package installed; no luck. My issue comes after successfully running the `./configure` script, during `make`. Currently I'm getting an error on the `postgis-3.4.2.tar.gz` package: `E0000 00:00:1713245269.277517 6670459 command_line_interface.cc:1534] Built-in generator --c_out specifies a maximum edition PROTO3 which is not the protoc maximum 2023. make[1]: *** [vector_tile.pb-c.c] Error 1 make: *** [all] Error 1`
> 
> I run the configure script like so: `eval ./configure `pg_config --configure`--with-pgconfig=/Users/marksadegi/.asdf/installs/postgres/16.2/bin/pg_config`
> 
> also tried setting the `PKG_CONFIG_PATH` env var as per the ./configure output instructions; no luck.
> 
> Here's my machine info: macOS: 14.4.1 chip: Apple M1 Pro
> 
> If anyone has more insight as to how to install `postgis` with an asdf postgres v 16.2 | 16.0 | 15.3 (any would work) install on a Mac M1 machine, I would super appreciate the insight!

Getting the same error when trying to install postgis, have you found any solutions yet?

**Comment by alexanderadam** [comment]
I had it working in earlier releases but now I'm getting the same error.
Even using older releases, like 3.1.x didn't work for me (they worked before on the same machine).

However, it seems to be related to [PostGIS issue 5730](https://trac.osgeo.org/postgis/ticket/5730) and you can disable protobuf to make it work.

So iust append `--without-protobuf` to your `./configure` command and you should be ready to go.

You might also want to have a look at [PostGIS Pull Request 772](https://github.com/postgis/postgis/pull/772).

**Comment by goughjo02** [comment]
anyone trying to do this with postgis installed with brew?
