### ISSUE TITLE
Make upgrading asdf more seamless

### ISSUE THREAD

**Issue by bbil** [smashedtoatoms/asdf-postgres#51]
**Is your feature request related to a problem? Please describe.**

On upgrading asdf, none of the postgres related shims were working, due to the `exec` call pointing to a specific version of `asdf`.

**Describe the solution you'd like**

Instead of pointing to a specific version of asdf, use a symlink like other asdf plugins.

pg_config
```
exec /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf exec "pg_config" "$@"
```

vs. node
```
exec /usr/local/opt/asdf/bin/asdf exec "node" "$@"
```

Node (and others) worked directly out of the box after the asdf upgrade without issue.

**Describe alternatives you've considered**

What got things working and able to continue on my day, was manually going in and changing the `exec` call on the shims that were failing. That got what I was doing immediately working, but I realized that it may break in a difference way later on. So, I uninstalled and re-installed postgres through asdf itself.

**Additional context**
This was on MacOS

**Comment by smashedtoatoms** [comment]
Any idea how other plugins are doing that?  I can go see if I can figure out what I'm doing wrong, but I can't get to it this weekend.

**Comment by smashedtoatoms** [comment]
I can't seem to duplicate this.  It worked fine on my last update.  I am going to have to figure out how others are doing this.

**Comment by smashedtoatoms** [comment]
I am sure this is still wrong, but I will not have time to address it.  I haven't noticed it, likely because I reinstall postgres so regularly.  If this is a problem for anyone, I would gladly accept a PR, but for now I am closing this with the recommendation that if your shims break, re-install postgres.  I'm really sorry.

**Comment by bbil** [comment]
Missed your comments, but apparently I see the closure :joy:. All good, I don't think I've seen any issues in a while.
