### ISSUE TITLE
Installation fails for on WSL2

### ISSUE THREAD

**Issue by thiagomajesk** [smashedtoatoms/asdf-postgres#54]
When I run ` uname -r` it returns `5.10.60.1-microsoft-standard-WSL2`, which doesn't seem to yield a valid package!? So what would be the best way to make it work for WSL2? I'm running Ubuntu 20.04.

```
sudo apt-get install linux-headers-$(uname -r) build-essential libssl-dev libreadline-dev zlib1g-dev libcurl4-openssl-dev uuid-dev
```

**Outputs**
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-5.10.60.1-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-headers-5.10.60.1-microsoft-standard-WSL2'
E: Couldn't find any package by regex 'linux-headers-5.10.60.1-microsoft-standard-WSL2'
```

**Comment by smashedtoatoms** [comment]
I am going to have to get a windows machine to try this out.  It looks like the wsl2 kernel does not allow modules to be loaded, which means you'll have to compile a kernel from source with the ms kernel patches.  I could be totally wrong though.  Maybe they include them another way.  Does it work if you skip that dependency?  If you install everything but the headers does it work?

**Comment by thiagomajesk** [comment]
Hi @smashedtoatoms, I've just tried installing the plugin without the headers and it did work.
Also installed postgres `latest` and managed to run some migrations on top of it, so I guess it does work properly.
 
I'm not sure however if it's necessary for something else, do I have to watch out for something? 
Tell me if you want me to run some tests for you so we can guarantee that this will work for other users.
