### ISSUE TITLE
Dependency needed to install on Fedora 35

### ISSUE THREAD

**Issue by brenoferreiralima** [smashedtoatoms/asdf-postgres#55]
**Describe the bug**

You need the package libuuid-devel on fedora 35 to install postgres 14.2 or you get a configure error.. and libuuid-devel is not listed in the dependencies list to install.

**Steps to reproduce**

try to install (asdf install) without the libuuid-devel installed.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 2FO** [comment]
Thanks, for the fix. I couldn't past the "missing uuid" config errors without it.

**Comment by smashedtoatoms** [comment]
I updated the docs.
