### ISSUE TITLE
Question: How to connect to db through GUI tool?

### ISSUE THREAD

**Issue by olimart** [smashedtoatoms/asdf-postgres#56]
Hi,
I'm using a tool `TablePlus` to access my dbs.
Wondering what is expected to create a new connection. I'm confused how to fill in the `Host/Socket` & `port` fields in particular.

Here is an example of what such tools expect. Thanks
![Capture d’écran, le 2022-03-02 à 15 37 56](https://user-images.githubusercontent.com/547754/156445691-9e9d0f94-a50a-413d-887d-415bef9af3c2.png)
.

**Comment by smashedtoatoms** [comment]
You should be able to start your database via the method specified in the README. It looks like the defaults are correct for a locally running db with the exception of the dbname, which you'll probably want to create yourself. You'll have to check the Postgres docs to see how to do that.

**Comment by olimart** [comment]
Thanks. It did help. Closing.
