### ISSUE TITLE
Auto symlink for /usr/local/opt/postgresql

### ISSUE THREAD

**Issue by CharlonTank** [smashedtoatoms/asdf-postgres#57]
**Describe the bug**
error:
ld: warning: directory not found for option '-L/usr/local/opt/postgresql/lib'

I had to create a symlink like that:
`➜  ln -s /usr/local/opt/postgresql/lib  /Users/yoyoyo/.asdf/installs/postgres/14.2/lib`
to be able to use most of my applications

**Steps to reproduce**
install for example diesel and run cargo, it needs: `/usr/local/opt/postgresql/lib` to point to something working and existing

**Expected behavior**

/usr/local/opt/postgresql/lib should point to the postgres version I'm currently using through asdf

**Screenshots**

<img width="670" alt="image" src="https://user-images.githubusercontent.com/4601603/159039746-94b67a96-dc30-4eb5-887f-680c3d1d615a.png">
**Additional context**

**Comment by smashedtoatoms** [comment]
That is not an opinion I am going to bake into this plugin.  If applications have db locations hard-coded, I would file issues against those applications to have the db location configurable.  Another option would be to use something other than asdf for those kinds of db installs.

**Comment by CharlonTank** [comment]
> That is not an opinion I am going to bake into this plugin. If applications have db locations hard-coded, I would file issues against those applications to have the db location configurable. Another option would be to use something other than asdf for those kinds of db installs.

Thank you for your answer, I'll create an issue into cargo/diesel
