### ISSUE TITLE
[Mac OSX] postgres could not perform collations because of missing uconv command.

### ISSUE THREAD

**Issue by monicalabbao** [smashedtoatoms/asdf-postgres#66]
I'm on a Mac OSX Ventura with ICU4C installed via Homebrew. However, when installing any version of postgres (14.1, 14.2, 15.1) using asdf, I could not perform the `uconv` command:

```
/Users/me/.asdf/plugins/postgres/bin/install: line 47: uconv: command not found
Building with options: --prefix=/Users/me/.asdf/installs/postgres/15.1     --with-uuid=e2fs     --with-openssl     --with-zlib     --with-libraries='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/openssl/lib:/opt/homebrew/opt/openssl@3/lib:/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/openssl/lib:/opt/homebrew/libressl/lib:/opt/homebrew/lib:/usr/local/lib:/usr/lib'     --with-includes='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/include:/opt/homebrew/opt/openssl/include:/opt/homebrew/include:/opt/homebrew/opt/openssl@3/include:/opt/homebrew/opt/openssl@1.1/include:/opt/homebrew/openssl/include:/opt/homebrew/libressl/include:/opt/homebrew/include:/usr/local/include:/usr/local/lib:/usr/lib'
```

Wondering where can I find `uconv` for MacOS if it won't recognize ICU4C, because I certainly have ICU4C:

```
Warning: icu4c 72.1 is already installed and up-to-date.
➜ brew list icu4c | grep uconv
/opt/homebrew/Cellar/icu4c/72.1/bin/uconv
/opt/homebrew/Cellar/icu4c/72.1/share/man/man1/uconv.1
```

Installing postgres with an explicit `PKG_CONFIG_PATH`(`PKG_CONFIG_PATH=$(brew --prefix icu4c)/lib/pkgconfig asdf install postgres 15.1`), or Installing the same plugin with the explicit `--with-icu` flag fails the installation of the plugin:

```
checking whether to build with ICU support... yes
checking for icu-uc icu-i18n... no
configure: error: in `/var/folders/zb/6v5_k5ld7cb6wj8syvznc9v40000gn/T/postgresql-15.1':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
```

I was hoping you could help me.

Thanks!

**Comment by monicalabbao** [comment]
Thank you for the linking solution! Though that's odd, even with the said extra config options, it won't add the `--with-icu` flag:

```
➜ POSTGRES_EXTRA_CONFIG_OPTIONS="--with-icu" asdf install postgres 15.1
** Resuming transfer from byte position 29778341
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   190  100   190    0     0     95      0  0:00:02  0:00:01  0:00:01    95
Building with options: --prefix=/Users/me/.asdf/installs/postgres/15.1     --with-uuid=e2fs     --with-openssl     --with-zlib     --with-libraries='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/lib:/opt/homebrew/opt/openssl/lib:/opt/homebrew/opt/openssl@3/lib:/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/openssl/lib:/opt/homebrew/libressl/lib:/opt/homebrew/lib:/usr/local/lib:/usr/lib'     --with-includes='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/include:/opt/homebrew/opt/openssl/include:/opt/homebrew/include:/opt/homebrew/opt/openssl@3/include:/opt/homebrew/opt/openssl@1.1/include:/opt/homebrew/openssl/include:/opt/homebrew/libressl/include:/opt/homebrew/include:/usr/local/include:/usr/local/lib:/usr/lib'
```

Though it does not complain that the uconv command is no longer found.

```
08:54:54.859 [info] execute "  CREATE COLLATION alphanumeric (provider = icu, locale = 'en-u-kn-true');\n"
2023-01-31 08:54:54.860 PST [78874] ERROR:  ICU is not supported in this build
2023-01-31 08:54:54.860 PST [78874] STATEMENT:    CREATE COLLATION alphanumeric (provider = icu, locale = 'en-u-kn-true');

** (Postgrex.Error) ERROR 0A000 (feature_not_supported) ICU is not supported in this build
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:352: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:289: Ecto.Migration.Runner.perform_operation/3
```

Though this might be a postgrex problem.

**Comment by smashedtoatoms** [comment]
Oh! Ok, so Postgres has this neat thing where they drop into pkg-config if they think they need to; but only for certain libraries and features.  If you added the icu4c lib to your linking path with `brew link icu4c --force`, you'll still have to add the --with-icu paths in the command to keep pkg-config from running.  

This is going to sound stupid, but try running `POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-icu" ICU_CFLAGS=" " ICU_LIBS=" " asdf install postgres 15.1`  

The existence of those environment variables being non-empty strings should stop pkg-config from running, but since the linked libs are in your default path, it should still build.

**Comment by smashedtoatoms** [comment]
Also, super-stoked to see you using Elixir!

**Comment by monicalabbao** [comment]
Thank you! This worked: `POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-icu" ICU_CFLAGS=" " ICU_LIBS=" " asdf install postgres 15.1`

Although, I had to do more than simply install Postgres 15.1. The `python` commands were resolving to Python 3. This made Postgres think that I am missing a ton of symlinks. So either I had to resolve all those symlinks one by one, or I just roll back my `python` commands back to Python 2. 

Thank you so much for your help and for engaging with me. May I close this issue now? Or do you have questions?

**Comment by smashedtoatoms** [comment]
I was leaving it open in case you had more questions.  I'll close it now.  I am glad it's working.

**Comment by sneko** [comment]
On my side reinstalling `icu4c` was doing nothing and running `brew link icu4c --force` was telling me `Refusing to link macOS provided/shadowed software: icu4c`.

So as explained by the command result I used:
```
PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig" asdf install postgres 16.2
```

And it worked 👍
