### ISSUE TITLE
Document where to look for config.log on installation failure

### ISSUE THREAD

**Issue by alexeyr-ci1** [smashedtoatoms/asdf-postgres#67]
When installation fails, the error says something like 
```
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.
```
The problem is that I do have readline installed (both with Homebrew and with apt-get). 

I found the correct `config.log` file in `/tmp/tmp.Egrr7jiygn/postgresql-15.1/config.log` (after some figuring out due to previous failing errors). Is it possible to do one of following (in order of my preference)?

1. Give the full path to `config.log` in the error message (probably not, I assume it comes from Postgres itself);
2. Include the build directory under `/tmp` in a separate message;
3. Mention how to find the file in README.

**Comment by smashedtoatoms** [comment]
Since I haven't experienced what you're experiencing, I am not in a great position to document it.  If you want to add a troubleshooting section to the docs though, or figure out a way to print out the tmp directory location, I'd be totally fine with that.

**Comment by stanhu** [comment]
https://github.com/smashedtoatoms/asdf-postgres/pull/73 should also solve this issue.

**Comment by smashedtoatoms** [comment]
I just merged @stanhu's PR.  @alexeyr-ci1, can you update to the latest asdf-postgres and try again and let us know if it behaves as expected?
