### ISSUE TITLE
how to access postgres environemt in the asdf?

### ISSUE THREAD

**Issue by luisxx123** [smashedtoatoms/asdf-postgres#70]
I am having an issue where I can't create a database due to the following error:
`createdb: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  role "luisgomes" does not exist`

In order to solve that, I ran `sudo -i -u postgres` and then `createuser -s -P luisgomes`. 
It gave me an `bash: createuser: command not found...` .

I asked chatGPT what should I do and it explained that createuser is available only on the postgresql created by **asdf**.
It also told me to run `asdf shell postgres 15.2` but nothing happened. (15.2 is the version I have installed)

What should I do now?

**Comment by rngadam** [comment]
Just for future reference, in case someone found this like I did:

the default setup has data/pg_hba.conf set to trust for local connections.

This means that you can connect to any user that exists in the database by just specifying that user. 

As the only user that exists initially is postgres, you have to use:

```
psql -U postgres
```

and then you can create a user to match your current user:

```
CREATE USER vscode;
ALTER USER vscode WITH SUPERUSER;
```

from then on, you can createdb and connect to that db.
