### ISSUE TITLE
psql tmp binary not cleaned up after successful install meaning reinstalls just reuse it on mac

### ISSUE THREAD

**Issue by DylanGriffith** [smashedtoatoms/asdf-postgres#72]
**Describe the bug**

Whenever a version of postgres is installed via asdf-postgres (on mac) it leaves behind a psql binary in `find $TMPDIR -name psql`. This same binary will be re-used if you `asdf uninstall` and `asdf install` again. This causes problems when you're trying to change [compiler options](https://github.com/smashedtoatoms/asdf-postgres#asdf-options) and in particular this is problematic for people trying to get `psql` to install with GNU readline instead of libedit.

**Steps to reproduce**

1. `asdf install postgres 13.8`
2. `asdf local postgres 13.8`
3. `otool -L $(asdf which psql)`
    ```
    ...
    /usr/lib/libedit.3.dylib
    ...
    ```
 4. Cry because `libedit` is no good
 5. `asdf uninstall postgres 13.8`
 6. Install again with readline flags (requires `readline` from homebrew):
     ```
     LDFLAGS="-L/opt/homebrew/opt/readline/lib" CPPFLAGS="-I/opt/homebrew/opt/readline/include" asdf install postgres 13.8
     ```
3. `otool -L $(asdf which psql)`
    ```
    ...
    /usr/lib/libedit.3.dylib
    ...
    ```

**Expected behavior**

We should be seeing:

```
$ otool -L $(asdf which psql)
...
	/opt/homebrew/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
...
```

**Screenshots**

**Additional context**

It seems like asdf plugins are meant to implement a [download script](https://asdf-vm.com/plugins/create.html#bin-download) (also see [the template](https://github.com/asdf-vm/asdf-plugin-template/blob/main/template/bin/download)). This allows them to do all their work in their and let asdf clean it up.

**Workaround**

For others (like myself) desperately trying to install psql with libreadline then this workaround will work for you:

1. `asdf uninstall postgres 13.8`
2. `find $TMPDIR -name psql`
3. `rm ...` (the psql binary found above)
4. `LDFLAGS="-L/opt/homebrew/opt/readline/lib" CPPFLAGS="-I/opt/homebrew/opt/readline/include" asdf install postgres 13.8 `

**Comment by DylanGriffith** [comment]
Also related to https://github.com/smashedtoatoms/asdf-postgres/issues/47 .

Thanks @smashedtoatoms to for this great tool! It has been really helpful lately while I'm testing many different Postgres versions.

Hopefully this bug report contains clear enough details to make the problem and solution clear.

**Comment by smashedtoatoms** [comment]
It looks like https://github.com/smashedtoatoms/asdf-postgres/pull/73 has the fix outlined.  I need to find the time to get it done.  I will take a look at this as soon as I can.  Feel free to take a stab at it if your bash scripting skills need some flexing.

**Comment by stanhu** [comment]
@smashedtoatoms To be clear, https://github.com/smashedtoatoms/asdf-postgres/pull/73 is a pull request that fixes this issue.
