### ISSUE TITLE
Compiles without ICU support

### ISSUE THREAD

**Issue by peterhippocarter** [smashedtoatoms/asdf-postgres#74]
**Is your feature request related to a problem? Please describe.**

Some projects require ICU support to work. This is included in other Postgres installations I've tried but not this one. This caused me some pain as I ended up having to uninstall this version and install the [postgresapp.com](postgresapp.com) version instead, which includes ICU support.

**Describe the solution you'd like**

It'd be nice if the installation here did include ICU support, or at least had the option to enable it clearly marked in the readme. As it stands there's no warning that by installing the version in this repo, you might end up with less project support than with other widely available distros. 

**Describe alternatives you've considered**

If there's some compelling reason(s) support should be omitted here, it would be nice to get a heads up that's the case and what the impact might be to development. Asdf is supposed to make developers' lives easier and that's pretty much its only reason for existing, so imo anything that's likely to have the opposite effect should at least be addressed in an obvious location.

**Additional context**

**Comment by smashedtoatoms** [comment]
This should be sorted out now.  Let me know if it is not the case.
