### ISSUE TITLE
list-all doesnt show any options

### ISSUE THREAD

**Issue by fcevado** [smashedtoatoms/asdf-postgres#8]

**Comment by smashedtoatoms** [comment]
Can you pull the latest and try again.  It should be working now.  ```~ % asdf list-all postgres
9.6.3
9.6.2
9.6.1
9.6.0
9.5.5
9.5.4
9.5.3
9.5.2
9.5.1
9.5.0
9.4.10
9.4.9
9.4.8
9.4.7
9.4.6
9.4.5
9.4.4
9.4.3
9.4.2
9.4.1```

**Comment by fcevado** [comment]
working now... thanks a lot :D... loved the initiative
