### ISSUE TITLE
OpenSSL and ReadLine not found

### ISSUE THREAD

**Issue by raulbonet** [smashedtoatoms/asdf-postgres#86]
**Describe the bug**

It seems that [this](https://github.com/smashedtoatoms/asdf-postgres/pull/81) MR broke our pipeline since it was deployed yesterday. 

We did not have any problem with OpenSSL or ReadLine, even if all of us are using mac. I guess the way it was fixed for some people broke it for others. 

Personally, I am using an M2 Macbook Pro with macOS Sonoma, but other colleagues are using M1.

**Comment by smashedtoatoms** [comment]
I am reverting it now, standby.

**Comment by smashedtoatoms** [comment]
Can you please send me the errors so I can investigate?

**Comment by raulbonet** [comment]
Thanks @smashedtoatoms 
I am not sure if there are any logs I can query, what I see in the terminal is just:
```
Could not find OpenSSL!
Could not find ReadLine!
```
Which are the custom errors of the MR

**Comment by smashedtoatoms** [comment]
It should be reverted.  If you could retry it with the latest and let me know, that would be great.

**Comment by smashedtoatoms** [comment]
My suspicion is, based on those errors, that your pipeline is doing something kind of non-standard, but the fact that it works with the old code and not the new makes me think the new code is too rigid.  I'll investigate when I get a chance.  Let me know if your error went away when you get a chance.

**Comment by raulbonet** [comment]
Checked with the reverted commit and now it works again, thank you.

By the way: now I am thinking that our CI uses Linux and it is also broken there

**Comment by smashedtoatoms** [comment]
I suspect the break is on the Linux side.  I am noticing that most Linux distros have a sane openssl story.  Apple's is an absolute tire fire, and everyone fixes it in a different way.  Almost every PR that "Fixes" openssl on Mac, breaks it for everyone else.  It's really hard to chase down.  The way it is now results in the fewest complaints; however, about once a year I get a PR that looks good and then breaks it in a new way.  It's that time of the year.  It's really hard for me to verify behavior on everyone's bespoke compiler chains.
