### ISSUE TITLE
Question: what's the recommended way of migrating databases between version changes

### ISSUE THREAD

**Issue by alexanderadam** [smashedtoatoms/asdf-postgres#89]
So a version upgrade in the `.tool-versions` will automatically lead to a new postgres installtion and hence new databases, right?
What's the recommended way of migrating the data to the new version too?

**Comment by smashedtoatoms** [comment]
There isn't a recommended way to do it for asdf-vm beyond what you would do with regular Postgres for your needs at the time.  For me, I'd probably use `pgdump` to move the data over to the new db.  

This project was originally conceived to allow me to build ephemeral Postgres instances per project and specify the version in the project itself.  My instances lived for ~5 minutes while tests ran and a few minutes after they were completed using ephemeral-pg.  Then asdf-vm got more popular and people started using it for their local installs in ways I never envisioned.  Sorry for the possibly pointless history, I just want you to know why it isn't in there.  All of this is a long-winded way of saying I would just use pgdump.
