### ISSUE TITLE
Regex used by versions_list doesn't match "v10.0"

### ISSUE THREAD

**Issue by jpayne** [smashedtoatoms/asdf-postgres#9]
The regex used to read all the Postgres versions at https://ftp.postgresql.org/pub/source/ and assign them to versions_list assumes that the version number will always be in the format "\d.\d.\d". However, the newest version of Postgres is in the format "10.0" (i.e. not "10.0.0"). There are also numerous other Postgres version numbers like this that the regex is not matching.

**Comment by smashedtoatoms** [comment]
So my regex foo is pretty weak, what do you think, something like this`\\d+.\\d+.?\\d?`?  That would work, but as with all regex, who know what else it might do.

**Comment by jpayne** [comment]
I've created a pull request with a modified regex. Seems to be working fine here.

**Comment by jpayne** [comment]
Thank you for merging the pull request, @smashedtoatoms. I was just able to successfully install Postgres v10.0.

Thanks for the great plugin.
