### ISSUE TITLE
pg_config CPPFLAGS and LDFLAGS become broken after mac os minor upgrade

### ISSUE THREAD

**Issue by nileshtrivedi** [smashedtoatoms/asdf-postgres#96]
I installed postgres 17.1 via asdf on mac os 15.1. Then I upgraded mac os to 15.2 along with Xcode CommandLineTools.

```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.2
BuildVersion:		24C101

$ which pg_config
/Users/nt/.asdf/shims/pg_config

$ asdf list postgres
 *17.1

$ ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
lrwxr-xr-x  1 root  wheel   14 Dec 28 21:33 MacOSX.sdk -> MacOSX15.2.sdk
drwxr-xr-x  7 root  wheel  224 Dec 28 21:34 MacOSX14.5.sdk
lrwxr-xr-x  1 root  wheel   14 Dec 28 21:33 MacOSX14.sdk -> MacOSX14.5.sdk
drwxr-xr-x  7 root  wheel  224 Nov 21 13:35 MacOSX15.2.sdk
lrwxr-xr-x  1 root  wheel   14 Dec 28 21:33 MacOSX15.sdk -> MacOSX15.2.sdk
```

However, `pg_config`'s `CPPFLAGS` and `LDFLAGS` still refer to `MacOSX15.1.sdk` which no longer exists:

```
$ pg_config --cppflags          
-I/opt/homebrew/Cellar/icu4c@76/76.1_1/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.1.sdk -I/opt/homebrew/opt/openssl/include -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@3.4/include -I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/include

$ pg_config --ldflags 
-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX15.1.sdk -L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/opt/openssl@3.4/lib -L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/lib -Wl,-dead_strip_dylibs
```

This breaks the ability to build postgres extensions like `pgvector`. See [this issue](https://github.com/pgvector/pgvector/issues/592) and [others](https://github.com/pgvector/pgvector/issues?q=is%3Aissue+stdio.h+is%3Aclosed).

The symlink `MacOSX15.sdk` does exist and it points to `MacOSX15.2.sdk`. 

If pg_config (i.e. postgres installed via asdf) had used `MacOSX15.sdk` instead of `MacOSX15.1.sdk` in `CPPFLAGS` and `LDFLAGS`, this breakage would have been avoided.

**Comment by smashedtoatoms** [comment]
I don't have any idea how to set that on build.  That is getting borked by something in the postgres makefile I suspect.  This needs to be fixed by them unless you know of a way for me to configure it reliably that isn't going to blow up in the future when they change something else.  Unfortunately, the current workaround seems to be to rebuild your current install, but I suspect that will be more stable than any hack I come up with.

**Comment by nileshtrivedi** [comment]
Fair enough, @smashedtoatoms. Will close the issue.

FWIW, a workaround is creating a symlink to a working SDK: 

```
$ cd /Library/Developer/CommandLineTools/SDKs
SDKs $ sudo ln -s MacOSX15.2.sdk MacOSX15.1.sdk
```
